Fixed: - Contact/User::isBlocked() needs to return boolean, but sometimes (strangely)   a NULL can come from database, so let's cast it
This tries to fix:
TypeError: "Return value of Friendica\Model\Contact\User::isBlocked() must be of the type bool, null returned"